### ISSUE TITLE
trojan: custom sni support

### ISSUE THREAD

**Issue by flyysquirrel** [Qv2ray/v2ray-rust#162]

**Comment by darsvador** [comment]
````toml
[[inbounds]]
addr = '0.0.0.0:12333'
tag = 'http-in-1'

[[inbounds]]
addr = '0.0.0.0:1089'
enable_udp = true
tag = 'socks-in-1'

[[outbounds]]
chain = [ 'sni', 'trojan' ]
tag = 'Default'

[[tls]]
sni = 'yoursni.com'
tag = 'sni'

[[trojan]]
addr = 'example.com:443'
password = 'example_password'
tag = "trojan"

````
